### ISSUE TITLE
Ported to Android

### ISSUE THREAD

**Issue by septs** [charlysan/pyrfidhid#4]
https://github.com/NiceLabs/usb-125khz-idrw

I want to record to README file

**Comment by septs** [comment]
@charlysan Request record the project README file

**Comment by charlysan** [comment]
@septs, are you asking me for permission to mention my project in your README file?

**Comment by septs** [comment]
I hope to mention `usb-125khz-idrw` project to your project.

**Comment by charlysan** [comment]
Okay, I will add a reference to your project in my Readme file.

**Comment by charlysan** [comment]
Done
